error: expected item, found keyword `let`
 --> /tmp/codegemma7b-int_arith-py-rs.rs:1:1
  |
1 | let yy = input1.try_into().unwrap().pow(input2.try_into().unwrap());
  | ^^^ consider using `const` or `static` instead of `let` for global variables

error: aborting due to 1 previous error

