Traceback (most recent call last):
  File "/var/folders/d3/zttsdsd50sjf25r6syczw4jh0000gq/T/tmpwevn384v/qwen2.5coder2b-int_arith-java-py.py", line 25, in <module>
    main()
  File "/var/folders/d3/zttsdsd50sjf25r6syczw4jh0000gq/T/tmpwevn384v/qwen2.5coder2b-int_arith-java-py.py", line 6, in main
    a = int(sys.argv[1])
            ~~~~~~~~^^^
IndexError: list index out of range
