Traceback (most recent call last):
  File "/var/folders/d3/zttsdsd50sjf25r6syczw4jh0000gq/T/tmpiim9j44b/yicoder2b-file_size-rs-py.py", line 18, in <module>
    main()
  File "/var/folders/d3/zttsdsd50sjf25r6syczw4jh0000gq/T/tmpiim9j44b/yicoder2b-file_size-rs-py.py", line 6, in main
    if len(sys.argv) != 2:
           ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'?
